from abc import ABC, abstractmethod


class BaseStrategy(ABC):
    """
    Abstract base class for tool calling strategies.
    Different models or modes (e.g., Qwen, JSON, Function Calling) can implement this.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """The name of the strategy."""
        pass

    @abstractmethod
    def get_system_prompt(self, tool_registry: dict) -> str:
        """
        Generates the system prompt including tool definitions.

        Args:
            tool_registry: Dictionary of tool names to tool instances.

        Returns:
            The formatted system prompt.
        """
        pass

    @abstractmethod
    def parse_tool_calls(self, text: str) -> list[dict]:
        """
        Parses tool calls from the model's output text.

        Args:
            text: The text generated by the model.

        Returns:
            A list of tool call dictionaries in the standard format:
            [{
                "id": ...,
                "type": "function",
                "function": {"name": ..., "arguments": ...}
            }]
        """
        pass
